A4OA-AA9R	Infinite lives
CDXA-AA3N	Infinite time, not in Training mode
BJNT-AADE	Start with 10 lives (not in 2P competitive mode)
CTNT-AADE	Start with 20 lives (not in 2P competitive mode)
GJNT-AADE	Start with 50 lives (not in 2P competitive mode)
BJNT-AAEE	Start with 10 lives - P1 (2P competitive mode)
CTNT-AAEE	Start with 20 lives - P1 (2P competitive mode)
GJNT-AAEE	Start with 50 lives - P1 (2P competitive mode)
BJNT-AAEL	Start with 10 lives - P2 (2P competitive mode)
CTNT-AAEL	Start with 20 lives - P2 (2P competitive mode)
GJNT-AAEL	Start with 50 lives - P2 (2P competitive mode)
BDBT-AA9A	You can use any special weapon at any time
A4CT-AA6A	Most enemies die with one hit
RENA-A60R	Start on level 2 (1 of 3)
9TNA-BGRT	Start on level 2 (2 of 3)
AENA-AAGW	Start on level 2 (3 of 3)
RENA-A60R	Start on level 3 (1 of 3)
9TNA-BGRT	Start on level 3 (2 of 3)
AJNA-AAGW	Start on level 3 (3 of 3)
RENA-A60R	Start on level 4 (1 of 3)
9TNA-BGRT	Start on level 4 (2 of 3)
ANNA-AAGW	Start on level 4 (3 of 3)
RENA-A60R	Start on level 5 (1 of 3)
9TNA-BGRT	Start on level 5 (2 of 3)
ATNA-AAGW	Start on level 5 (3 of 3)
RENA-A60R	Start on level 6 (1 of 3)
9TNA-BGRT	Start on level 6 (2 of 3)
AYNA-AAGW	Start on level 6 (3 of 3)
RENA-A60R	Start on level 7 (1 of 3)
9TNA-BGRT	Start on level 7 (2 of 3)
A2NA-AAGW	Start on level 7 (3 of 3)
RENA-A60R	Start on level 8 (1 of 3)
9TNA-BGRT	Start on level 8 (2 of 3)
A6NA-AAGW	Start on level 8 (3 of 3)
HAVA-BAT0	Infinite health (1 of 2)
C6VA-AX22	Infinite health (2 of 2)
CWBA-AXW6	No enemies
A36T-AA62	Never get caught
