RF0T-A60J	Pitchers don't get tired
RF0T-A60J	Pitchers don't get tired  (alt)
AKSA-AA3E	Infinite innings
AKSA-AA3E	Infinite innings (alt)
AL5A-AA6A	Infinite outs (1 of 2)
AK5T-AA9A	Infinite outs (2 of 2)
AL5T-AA9E	Infinite outs (alt) (1 of 2)
AL6A-AA7R	Infinite outs (alt) (2 of 2)
AK5T-AA7R	Infinite strikes
AK5T-AA7W	Infinite strikes (alt)
AK5T-AA6A	Infinite balls
AK5T-AA6E	Infinite balls (alt)
AF5T-AAF8	Only need 1 strike for a strikeout (1 of 2)
AF2T-AADJ	Only need 1 strike for a strikeout (2 of 2)
AF2T-AADN	Only need 1 strike for a strikeout (alt) (1 of 3)
AF5T-AAGC	Only need 1 strike for a strikeout (alt) (2 of 3)
AGGA-AAG8	Only need 1 strike for a strikeout (alt) (3 of 3)
AK5T-AAF8	Only need 2 strikes for a strikeout (1 of 2)
AK2T-AADJ	Only need 2 strikes for a strikeout (2 of 2)
AK2T-AADN	Only need 2 strikes for a strikeout (alt) (1 of 3)
AK5T-AAGC	Only need 2 strikes for a strikeout (alt) (2 of 3)
ALGA-AAG8	Only need 2 strikes for a strikeout (alt) (3 of 3)
AV5T-AAF8	Must get 4 strikes for a strikeout (1 of 2)
AV2T-AADJ	Must get 4 strikes for a strikeout (2 of 2)
AV2T-AADN	Must get 4 strikes for a strikeout (alt) (1 of 3)
AV5T-AAGC	Must get 4 strikes for a strikeout (alt) (2 of 3)
AWGA-AAG8	Must get 4 strikes for a strikeout (alt) (3 of 3)
AZ5T-AAF8	Must get 5 strikes for a strikeout (1 of 2)
AZ2T-AADJ	Must get 5 strikes for a strikeout (2 of 2)
AZ2T-AADN	Must get 5 strikes for a strikeout (alt) (1 of 3)
AZ5T-AAGC	Must get 5 strikes for a strikeout (alt) (2 of 3)
A0GA-AAG8	Must get 5 strikes for a strikeout (alt) (3 of 3)
AF5T-AAE2	Only need 1 ball for a walk (1 of 5)
AF2T-AAEA	Only need 1 ball for a walk (2 of 5)
AGHT-AABC	Only need 1 ball for a walk (3 of 5)
AGNA-AAAW	Only need 1 ball for a walk (4 of 5)
AGSA-AAHA	Only need 1 ball for a walk (5 of 5)
AF2T-AAEE	Only need 1 ball for a walk (alt) (1 of 5)
AF5T-AAE6	Only need 1 ball for a walk (alt) (2 of 5)
AGHT-AADJ	Only need 1 ball for a walk (alt) (3 of 5)
AGNA-AAC2	Only need 1 ball for a walk (alt) (4 of 5)
AGST-AACY	Only need 1 ball for a walk (alt) (5 of 5)
AK5T-AAE2	Only need 2 balls for a walk (1 of 5)
AK2T-AAEA	Only need 2 balls for a walk (2 of 5)
ALHT-AABC	Only need 2 balls for a walk (3 of 5)
ALNA-AAAW	Only need 2 balls for a walk (4 of 5)
ALSA-AAHA	Only need 2 balls for a walk (5 of 5)
AK2T-AAEE	Only need 2 balls for a walk (alt) (1 of 5)
AK5T-AAE6	Only need 2 balls for a walk (alt) (2 of 5)
ALHT-AADJ	Only need 2 balls for a walk (alt) (3 of 5)
ALNA-AAC2	Only need 2 balls for a walk (alt) (4 of 5)
ALST-AACY	Only need 2 balls for a walk (alt) (5 of 5)
AP5T-AAE2	Only need 3 balls for a walk (1 of 5)
AP2T-AAEA	Only need 3 balls for a walk (2 of 5)
ARHT-AABC	Only need 3 balls for a walk (3 of 5)
ARNA-AAAW	Only need 3 balls for a walk (4 of 5)
ARSA-AAHA	Only need 3 balls for a walk (5 of 5)
AP2T-AAEE	Only need 3 balls for a walk (alt) (1 of 5)
AP5T-AAE6	Only need 3 balls for a walk (alt) (2 of 5)
ARHT-AADJ	Only need 3 balls for a walk (alt) (3 of 5)
ARNA-AAC2	Only need 3 balls for a walk (alt) (4 of 5)
ARST-AACY	Only need 3 balls for a walk (alt) (5 of 5)
AZ5T-AAE2	Need 5 balls for a walk (1 of 5)
AZ2T-AAEA	Need 5 balls for a walk (2 of 5)
A0HT-AABC	Need 5 balls for a walk (3 of 5)
A0NA-AAAW	Need 5 balls for a walk (4 of 5)
A0SA-AAHA	Need 5 balls for a walk (5 of 5)
AZ2T-AAEE	Need 5 balls for a walk (alt) (1 of 5)
AZ5T-AAE6	Need 5 balls for a walk (alt) (2 of 5)
A0HT-AADJ	Need 5 balls for a walk (alt) (3 of 5)
A0NA-AAC2	Need 5 balls for a walk (alt) (4 of 5)
A0ST-AACY	Need 5 balls for a walk (alt) (5 of 5)
A35T-AAE2	Need 6 balls for a walk (1 of 5)
A32T-AAEA	Need 6 balls for a walk (2 of 5)
A4HT-AABC	Need 6 balls for a walk (3 of 5)
A4NA-AAAW	Need 6 balls for a walk (4 of 5)
A4SA-AAHA	Need 6 balls for a walk (5 of 5)
A32T-AAEE	Need 6 balls for a walk (alt) (1 of 5)
A35T-AAE6	Need 6 balls for a walk (alt) (2 of 5)
A4HT-AADJ	Need 6 balls for a walk (alt) (3 of 5)
A4NA-AAC2	Need 6 balls for a walk (alt) (4 of 5)
A4ST-AACY	Need 6 balls for a walk (alt) (5 of 5)
