PPGA-AEDL	Rounds last 30 seconds instead of 1:30
2PGA-AJDL	Rounds last 1 minute
RPGA-AWDL	Rounds last 2 minutes
EPGA-A6DL	Rounds last 3 minutes
TPGA-BRDL	Rounds last 5 minutes
6PGA-AAML	Rounds last 7 minutes
57GA-A6ML	Rounds last 9 minutes, 59 seconds
APDA-AADJ	Knockout count is 3 instead of 10 (1 of 3)
APHT-AAEN	Knockout count is 3 instead of 10 (2 of 3)
APHT-AAC6	Knockout count is 3 instead of 10 (3 of 3)
AZDA-AADJ	Knockout count is 5 (1 of 3)
AZHT-AAEN	Knockout count is 5 (2 of 3)
AZHT-AAC6	Knockout count is 5 (3 of 3)
A7DA-AADJ	Knockout count is 7 (1 of 3)
A7HT-AAEN	Knockout count is 7 (2 of 3)
A7HT-AAC6	Knockout count is 7 (3 of 3)
BFDA-AADJ	Knockout count is 9 (1 of 3)
BFHT-AAEN	Knockout count is 9 (2 of 3)
BFHT-AAC6	Knockout count is 9 (3 of 3)
P3WT-BFXR	P1's damage meter recovers more slowly (1 of 4)
0BWT-B25T	P1's damage meter recovers more slowly (2 of 4)
AEAT-AACE	P1's damage meter recovers more slowly (3 of 4)
AJAT-AAGE	P1's damage meter recovers more slowly (4 of 4)
P3WT-BFXR	P1's damage meter recovers faster (1 of 4)
0BWT-B25T	P1's damage meter recovers faster (2 of 4)
CAAT-AACE	P1's damage meter recovers faster (3 of 4)
AJAT-AAGE	P1's damage meter recovers faster (4 of 4)
P3WT-BFXR	P1's damage meter recovers much faster (1 of 4)
0BWT-B25T	P1's damage meter recovers much faster (2 of 4)
JAAT-AACE	P1's damage meter recovers much faster (3 of 4)
AJAT-AAGE	P1's damage meter recovers much faster (4 of 4)
P3WT-BFXR	P2's damage meter recovers more slowly (1 of 4)
0BWT-B25T	P2's damage meter recovers more slowly (2 of 4)
AJAT-AACE	P2's damage meter recovers more slowly (3 of 4)
AEAT-AAGE	P2's damage meter recovers more slowly (4 of 4)
P3WT-BFXR	P2's damage meter recovers faster (1 of 4)
0BWT-B25T	P2's damage meter recovers faster (2 of 4)
AJAT-AACE	P2's damage meter recovers faster (3 of 4)
CAAT-AAGE	P2's damage meter recovers faster (4 of 4)
P3WT-BFXR	P2's damage meter recovers much faster (1 of 4)
0BWT-B25T	P2's damage meter recovers much faster (2 of 4)
AJAT-AACE	P2's damage meter recovers much faster (3 of 4)
JAAT-AAGE	P2's damage meter recovers much faster (4 of 4)
734T-ABYG	P1 scores fewer points (1 of 4)
YB4T-B26J	P1 scores fewer points (2 of 4)
ATAT-AABY	P1 scores fewer points (3 of 4)
BJAT-AAFY	P1 scores fewer points (4 of 4)
734T-ABYG	P1 scores more points (1 of 4)
YB4T-B26J	P1 scores more points (2 of 4)
EAAT-AABY	P1 scores more points (3 of 4)
BJAT-AAFY	P1 scores more points (4 of 4)
734T-ABYG	P2 scores fewer points (1 of 4)
YB4T-B26J	P2 scores fewer points (2 of 4)
BJAT-AABY	P2 scores fewer points (3 of 4)
ATAT-AAFY	P2 scores fewer points (4 of 4)
734T-ABYG	P2 scores more points (1 of 4)
YB4T-B26J	P2 scores more points (2 of 4)
BJAT-AABY	P2 scores more points (3 of 4)
EAAT-AAFY	P2 scores more points (4 of 4)
CTLT-AAC0	Choose 1 to 19 rounds instead of 1 to 12 on options screen (1 of 2)
CNLT-AAFE	Choose 1 to 19 rounds instead of 1 to 12 on options screen (2 of 2)
