AVDA-AA24	Infinite energy
BVDA-AA5G	Infinite lives
CX1T-GA5C	Infinite gas on the river
DBCT-AAA8	Start with 75% health (1 of 2)
DBDA-AAAW	Start with 75% health (2 of 2)
CBCT-AAA8	Start with 50% health (1 of 2)
CBDA-AAAW	Start with 50% health (2 of 2)
BBCT-AAA8	Start with 25% health (1 of 2)
BBDA-AAAW	Start with 25% health (2 of 2)
AFCT-AAA0	Start with 1 life
AKCT-AAA0	Start with 2 lives
ABDA-AAG2	Set 1 - Start with 0 blue-banded darts
AFDA-AAG2	Set 1 - Start with 1 blue-banded dart
BKDA-AAG2	Set 1 - Start with 10 blue-banded darts
B7DA-AAG2	Set 1 - Start with 15 blue-banded darts
GKDA-AAG2	Set 1 - Start with 50 blue-banded darts
J3DA-AAG2	Set 1 - Start with 70 blue-banded darts
NPDA-AAG2	Set 1 - Start with 99 blue-banded darts
AFDA-AAG2	Set 1 - Start with 1 red-banded dart (1 of 2)
AKDA-AAG4	Set 1 - Start with 1 red-banded dart (2 of 2)
BKDA-AAG2	Set 1 - Start with 10 red-banded darts (1 of 2)
AKDA-AAG4	Set 1 - Start with 10 red-banded darts (2 of 2)
B7DA-AAG2	Set 1 - Start with 15 red-banded darts (1 of 2)
AKDA-AAG4	Set 1 - Start with 15 red-banded darts (2 of 2)
GKDA-AAG2	Set 1 - Start with 50 red-banded darts (1 of 2)
AKDA-AAG4	Set 1 - Start with 50 red-banded darts (2 of 2)
J3DA-AAG2	Set 1 - Start with 70 red-banded darts (1 of 2)
AKDA-AAG4	Set 1 - Start with 70 red-banded darts (2 of 2)
NPDA-AAG2	Set 1 - Start with 99 red-banded darts (1 of 2)
AKDA-AAG4	Set 1 - Start with 99 red-banded darts (2 of 2)
AFDA-AAG2	Set 1 - Start with 1 gas grenade (1 of 2)
AVDA-AAG4	Set 1 - Start with 1 gas grenade (2 of 2)
BKDA-AAG2	Set 1 - Start with 10 gas grenades (1 of 2)
AVDA-AAG4	Set 1 - Start with 10 gas grenades (2 of 2)
B7DA-AAG2	Set 1 - Start with 15 gas grenades (1 of 2)
AVDA-AAG4	Set 1 - Start with 15 gas grenades (2 of 2)
GKDA-AAG2	Set 1 - Start with 50 gas grenades (1 of 2)
AVDA-AAG4	Set 1 - Start with 50 gas grenades (2 of 2)
J3DA-AAG2	Set 1 - Start with 70 gas grenades (1 of 2)
AVDA-AAG4	Set 1 - Start with 70 gas grenades (2 of 2)
NPDA-AAG2	Set 1 - Start with 99 gas grenades (1 of 2)
AVDA-AAG4	Set 1 - Start with 99 gas grenades (2 of 2)
AFDA-AAG2	Set 1 - Start with 1 flash grenade (1 of 2)
AZDA-AAG4	Set 1 - Start with 1 flash grenade (2 of 2)
BKDA-AAG2	Set 1 - Start with 10 flash grenades (1 of 2)
AZDA-AAG4	Set 1 - Start with 10 flash grenades (2 of 2)
B7DA-AAG2	Set 1 - Start with 15 flash grenades (1 of 2)
AZDA-AAG4	Set 1 - Start with 15 flash grenades (2 of 2)
GKDA-AAG2	Set 1 - Start with 50 flash grenades (1 of 2)
AZDA-AAG4	Set 1 - Start with 50 flash grenades (2 of 2)
J3DA-AAG2	Set 1 - Start with 70 flash grenades (1 of 2)
AZDA-AAG4	Set 1 - Start with 70 flash grenades (2 of 2)
NPDA-AAG2	Set 1 - Start with 99 flash grenades (1 of 2)
AZDA-AAG4	Set 1 - Start with 99 flash grenades (2 of 2)
AFDA-AAG2	Set 1 - Start with 1 concussion grenade (1 of 2)
A7DA-AAG4	Set 1 - Start with 1 concussion grenade (2 of 2)
BKDA-AAG2	Set 1 - Start with 10 concussion grenades (1 of 2)
A7DA-AAG4	Set 1 - Start with 10 concussion grenades (2 of 2)
B7DA-AAG2	Set 1 - Start with 15 concussion grenades (1 of 2)
A7DA-AAG4	Set 1 - Start with 15 concussion grenades (2 of 2)
GKDA-AAG2	Set 1 - Start with 50 concussion grenades (1 of 2)
A7DA-AAG4	Set 1 - Start with 50 concussion grenades (2 of 2)
J3DA-AAG2	Set 1 - Start with 70 concussion grenades (1 of 2)
A7DA-AAG4	Set 1 - Start with 70 concussion grenades (2 of 2)
NPDA-AAG2	Set 1 - Start with 99 concussion grenades (1 of 2)
A7DA-AAG4	Set 1 - Start with 99 concussion grenades (2 of 2)
AFDA-AAG2	Set 1 - Start with 1 rocket (1 of 2)
A3DA-AAG4	Set 1 - Start with 1 rocket (2 of 2)
BKDA-AAG2	Set 1 - Start with 10 rockets (1 of 2)
A3DA-AAG4	Set 1 - Start with 10 rockets (2 of 2)
B7DA-AAG2	Set 1 - Start with 15 rockets (1 of 2)
A3DA-AAG4	Set 1 - Start with 15 rockets (2 of 2)
GKDA-AAG2	Set 1 - Start with 50 rockets (1 of 2)
A3DA-AAG4	Set 1 - Start with 50 rockets (2 of 2)
J3DA-AAG2	Set 1 - Start with 70 rockets (1 of 2)
A3DA-AAG4	Set 1 - Start with 70 rockets (2 of 2)
NPDA-AAG2	Set 1 - Start with 99 rockets (1 of 2)
A3DA-AAG4	Set 1 - Start with 99 rockets (2 of 2)
ABDA-AAG8	Set 2 - Start with 0 stun gun shots
AFDA-AAG8	Set 2 - Start with 1 stun gun shot
BKDA-AAG8	Set 2 - Start with 10 stun gun shots
B7DA-AAG8	Set 2 - Start with 15 stun gun shots
GKDA-AAG8	Set 2 - Start with 50 stun gun shots
J3DA-AAG8	Set 2 - Start with 70 stun gun shots
NPDA-AAG8	Set 2 - Start with 99 stun gun shots
AFDA-AAG8	Set 2 - Start with 1 red-banded dart (1 of 2)
AKDA-AAHA	Set 2 - Start with 1 red-banded dart (2 of 2)
BKDA-AAG8	Set 2 - Start with 10 red-banded darts (1 of 2)
AKDA-AAHA	Set 2 - Start with 10 red-banded darts (2 of 2)
B7DA-AAG8	Set 2 - Start with 15 red-banded darts (1 of 2)
AKDA-AAHA	Set 2 - Start with 15 red-banded darts (2 of 2)
GKDA-AAG8	Set 2 - Start with 50 red-banded darts (1 of 2)
AKDA-AAHA	Set 2 - Start with 50 red-banded darts (2 of 2)
J3DA-AAG8	Set 2 - Start with 70 red-banded darts (1 of 2)
AKDA-AAHA	Set 2 - Start with 70 red-banded darts (2 of 2)
NPDA-AAG8	Set 2 - Start with 99 red-banded darts (1 of 2)
AKDA-AAHA	Set 2 - Start with 99 red-banded darts (2 of 2)
AFDA-AAG8	Set 2 - Start with 1 gas grenade (1 of 2)
AVDA-AAHA	Set 2 - Start with 1 gas grenade (2 of 2)
BKDA-AAG8	Set 2 - Start with 10 gas grenades (1 of 2)
AVDA-AAHA	Set 2 - Start with 10 gas grenades (2 of 2)
B7DA-AAG8	Set 2 - Start with 15 gas grenades (1 of 2)
AVDA-AAHA	Set 2 - Start with 15 gas grenades (2 of 2)
GKDA-AAG8	Set 2 - Start with 50 gas grenades (1 of 2)
AVDA-AAHA	Set 2 - Start with 50 gas grenades (2 of 2)
J3DA-AAG8	Set 2 - Start with 70 gas grenades (1 of 2)
AVDA-AAHA	Set 2 - Start with 70 gas grenades (2 of 2)
NPDA-AAG8	Set 2 - Start with 99 gas grenades (1 of 2)
AVDA-AAHA	Set 2 - Start with 99 gas grenades (2 of 2)
AFDA-AAG8	Set 2 - Start with 1 flash grenade (1 of 2)
AZDA-AAHA	Set 2 - Start with 1 flash grenade (2 of 2)
BKDA-AAG8	Set 2 - Start with 10 flash grenades (1 of 2)
AZDA-AAHA	Set 2 - Start with 10 flash grenades (2 of 2)
B7DA-AAG8	Set 2 - Start with 15 flash grenades (1 of 2)
AZDA-AAHA	Set 2 - Start with 15 flash grenades (2 of 2)
GKDA-AAG8	Set 2 - Start with 50 flash grenades (1 of 2)
AZDA-AAHA	Set 2 - Start with 50 flash grenades (2 of 2)
J3DA-AAG8	Set 2 - Start with 70 flash grenades (1 of 2)
AZDA-AAHA	Set 2 - Start with 70 flash grenades (2 of 2)
NPDA-AAG8	Set 2 - Start with 99 flash grenades (1 of 2)
AZDA-AAHA	Set 2 - Start with 99 flash grenades (2 of 2)
AFDA-AAG8	Set 2 - Start with 1 concussion grenade (1 of 2)
A7DA-AAHA	Set 2 - Start with 1 concussion grenade (2 of 2)
BKDA-AAG8	Set 2 - Start with 10 concussion grenades (1 of 2)
A7DA-AAHA	Set 2 - Start with 10 concussion grenades (2 of 2)
B7DA-AAG8	Set 2 - Start with 15 concussion grenades (1 of 2)
A7DA-AAHA	Set 2 - Start with 15 concussion grenades (2 of 2)
GKDA-AAG8	Set 2 - Start with 50 concussion grenades (1 of 2)
A7DA-AAHA	Set 2 - Start with 50 concussion grenades (2 of 2)
J3DA-AAG8	Set 2 - Start with 70 concussion grenades (1 of 2)
A7DA-AAHA	Set 2 - Start with 70 concussion grenades (2 of 2)
NPDA-AAG8	Set 2 - Start with 99 concussion grenades (1 of 2)
A7DA-AAHA	Set 2 - Start with 99 concussion grenades (2 of 2)
AFDA-AAG8	Set 2 - Start with 1 rocket (1 of 2)
A3DA-AAHA	Set 2 - Start with 1 rocket (2 of 2)
BKDA-AAG8	Set 2 - Start with 10 rockets (1 of 2)
A3DA-AAHA	Set 2 - Start with 10 rockets (2 of 2)
B7DA-AAG8	Set 2 - Start with 15 rockets (1 of 2)
A3DA-AAHA	Set 2 - Start with 15 rockets (2 of 2)
GKDA-AAG8	Set 2 - Start with 50 rockets (1 of 2)
A3DA-AAHA	Set 2 - Start with 50 rockets (2 of 2)
J3DA-AAG8	Set 2 - Start with 70 rockets (1 of 2)
A3DA-AAHA	Set 2 - Start with 70 rockets (2 of 2)
NPDA-AAG8	Set 2 - Start with 99 rockets (1 of 2)
A3DA-AAHA	Set 2 - Start with 99 rockets (2 of 2)
BLEA-8A8L	High charge stun gun shot doesn't use as much ammo (1 of 2)
BAET-8A5J	High charge stun gun shot doesn't use as much ammo (2 of 2)
AD7A-GTBC	Each gas can worth 1/2 normal amount of gas
AD7A-G2BC	Each gas can worth 3/4 normal amount of gas
AD7A-GAKC	Each gas can worth 2x normal amount of gas
AD7A-HAKC	Each gas can worth 3x normal amount of gas
AJMA-JA7G	Grant starts on Level 2 (power station) (1 of 3)
9TMA-KGFL	Grant starts on Level 2 (power station) (2 of 3)
AEMA-JAFN	Grant starts on Level 2 (power station) (3 of 3)
AJMA-JA7G	Grant starts on Level 3 (power station) (1 of 3)
9TMA-KGFL	Grant starts on Level 3 (power station) (2 of 3)
AJMA-JAFN	Grant starts on Level 3 (power station) (3 of 3)
AJMA-JA7G	Grant starts on Level 4 (power station) (1 of 3)
9TMA-KGFL	Grant starts on Level 4 (power station) (2 of 3)
ANMA-JAFN	Grant starts on Level 4 (power station) (3 of 3)
AJMA-JA7G	Grant starts on Level 5 (river) (1 of 3)
9TMA-KGFL	Grant starts on Level 5 (river) (2 of 3)
ATMA-JAFN	Grant starts on Level 5 (river) (3 of 3)
AJMA-JA7G	Grant starts on Level 6 (pump station) (1 of 3)
9TMA-KGFL	Grant starts on Level 6 (pump station) (2 of 3)
AYMA-JAFN	Grant starts on Level 6 (pump station) (3 of 3)
AJMA-JA7G	Grant starts on Level 7 (canyon) (1 of 3)
9TMA-KGFL	Grant starts on Level 7 (canyon) (2 of 3)
A2MA-JAFN	Grant starts on Level 7 (canyon) (3 of 3)
AJMA-JA7G	Grant starts on Level 8 (volcano) (1 of 3)
9TMA-KGFL	Grant starts on Level 8 (volcano) (2 of 3)
A6MA-JAFN	Grant starts on Level 8 (volcano) (3 of 3)
AJMA-JA7G	Grant starts on Level 9 (main hall) (1 of 3)
9TMA-KGFL	Grant starts on Level 9 (main hall) (2 of 3)
BAMA-JAFN	Grant starts on Level 9 (main hall) (3 of 3)
AJMA-JA7G	Grant starts on Level 10 (main hall) (1 of 3)
9TMA-KGFL	Grant starts on Level 10 (main hall) (2 of 3)
BEMA-JAFN	Grant starts on Level 10 (main hall) (3 of 3)
AJMA-JA7G	Grant starts on Level 11 (main hall) (1 of 3)
9TMA-KGFL	Grant starts on Level 11 (main hall) (2 of 3)
BJMA-JAFN	Grant starts on Level 11 (main hall) (3 of 3)
AJMA-JA7G	Grant starts on Level 12 (main hall) (1 of 3)
9TMA-KGFL	Grant starts on Level 12 (main hall) (2 of 3)
BNMA-JAFN	Grant starts on Level 12 (main hall) (3 of 3)
AJMA-JA7G	Grant starts on Level 13 (main hall) (1 of 3)
9TMA-KGFL	Grant starts on Level 13 (main hall) (2 of 3)
BTMA-JAFN	Grant starts on Level 13 (main hall) (3 of 3)
B3JA-JAB8	Raptor starts on Level 2 (power station)
B7JA-JAB8	Raptor starts on Level 3 (pump station)
CBJA-JAB8	Raptor starts on Level 4 (canyon)
CFJA-JAB8	Raptor starts on Level 5 (main hall)
CKJA-JAB8	Raptor starts on Level 6 (main hall)
CPJA-JAB8	Raptor starts on Level 7 (main hall)
CVJA-JAB8	Raptor starts on Level 8 (main hall)
CZJA-JAB8	Raptor starts on Level 9 (main hall)
