 
RH9A-R6ZA	Master code - Must be entered
STJT-BLM0	Each round begins at hole xx (1 of 3)
MAJT-AJD4	Each round begins at hole xx (2 of 3)
AEJT-AAD2	Each round begins at hole 2 (3 of 3)
AJJT-AAD2	Each round begins at hole 3 (3 of 3)
ANJT-AAD2	Each round begins at hole 4 (3 of 3)
ATJT-AAD2	Each round begins at hole 5 (3 of 3)
AYJT-AAD2	Each round begins at hole 6 (3 of 3)
A2JT-AAD2	Each round begins at hole 7 (3 of 3)
A6JT-AAD2	Each round begins at hole 8 (3 of 3)
BAJT-AAD2	Each round begins at hole 9 (3 of 3)
BEJT-AAD2	Each round begins at hole 10 (3 of 3)
BJJT-AAD2	Each round begins at hole 11 (3 of 3)
BNJT-AAD2	Each round begins at hole 12 (3 of 3)
BTJT-AAD2	Each round begins at hole 13 (3 of 3)
BYJT-AAD2	Each round begins at hole 14 (3 of 3)
B2JT-AAD2	Each round begins at hole 15 (3 of 3)
B6JT-AAD2	Each round begins at hole 16 (3 of 3)
CAJT-AAD2	Each round begins at hole 17 (3 of 3)
CEJT-AAD2	Each round begins at hole 18 (3 of 3)
AE5A-AACC 	Each round ends after hole 1 (1 of 2)
AFTT-AAD6	Each round ends after hole 1 (2 of 2)
AJ5A-AACC	Each round ends after hole 2 (1 of 2)
AKTT-AAD6	Each round ends after hole 2 (2 of 2)
AN5A-AACC	Each round ends after hole 3 (1 of 2)
APTT-AAD6	Each round ends after hole 3 (2 of 2)
AT5A-AACC 	Each round ends after hole 4 (1 of 2)
AVTT-AAD6	Each round ends after hole 4 (2 of 2)
AY5A-AACC 	Each round ends after hole 5 (1 of 2)
AZTT-AAD6	Each round ends after hole 5 (2 of 2)
A25A-AACC	Each round ends after hole 6 (1 of 2)
A3TT-AAD6	Each round ends after hole 6 (2 of 2)
A65A-AACC 	Each round ends after hole 7 (1 of 2)
A7TT-AAD6	Each round ends after hole 7 (2 of 2)
BA5A-AACC	Each round ends after hole 8 (1 of 2)
BBTT-AAD6	Each round ends after hole 8 (2 of 2)
BE5A-AACC	Each round ends after hole 9 (1 of 2)
BFTT-AAD6	Each round ends after hole 9 (2 of 2)
BJ5A-AACC	Each round ends after hole 10 (1 of 2)
BKTT-AAD6	Each round ends after hole 10 (2 of 2)
BN5A-AACC	Each round ends after hole 11 (1 of 2)
BPTT-AAD6	Each round ends after hole 11 (2 of 2)
BT5A-AACC	Each round ends after hole 12 (1 of 2)
BVTT-AAD6	Each round ends after hole 12 (2 of 2)
BY5A-AACC	Each round ends after hole 13 (1 of 2)
BZTT-AAD6	Each round ends after hole 13 (2 of 2)
B25A-AACC	Each round ends after hole 14 (1 of 2)
B3TT-AAD6	Each round ends after hole 14 (2 of 2)
B65A-AACC	Each round ends after hole 15 (1 of 2)
B7TT-AAD6	Each round ends after hole 15 (2 of 2)
CA5A-AACC	Each round ends after hole 16 (1 of 2)
CBTT-AAD6	Each round ends after hole 16 (2 of 2)
CE5A-AACC	Each round ends after hole 17 (1 of 2)
CFTT-AAD6	Each round ends after hole 17 (2 of 2)
EAKA-BJ26	Top 32 scores make first round cut instead of top 48 (tourament mode)
FAKA-BJ26	Top 40 scores make first round cut (tourament mode)
JAKA-BJ26	Top 64 scores make first round cut (tourament mode)
FAKA-BJ3A	Top 40 scores make second and third round cuts instead of top 32 (tourament mode)	
GAKA-BJ3A	Top 48 scores make second and third round cuts (tourament mode)
JAKA-BJ3A	Top 64 scores make second and third round cuts (tourament mode)
GTKA-BEZ2 + B2KA-AVF4 + A2KA-AA76	Everybody always makes the cut (tourament mode)
B8FT-AABA + ED0T-SLRA	Golf bag holds 15 clubs instead of 14
CCFT-AABA + ED0T-SNRA	Golf bag holds 16 clubs
CGFT-AABA	Golf bag holds 17 clubs