AJKA-CAHR	Game begins with inning 2
ANKA-CAHR	Game begins with inning 3
ATKA-CAHR	Game begins with inning 4
AYKA-CAHR	Game begins with inning 5
A2KA-CAHR	Game begins with inning 6
A6KA-CAHR	Game begins with inning 7
BAKA-CAHR	Game begins with inning 8
BEKA-CAHR	Game begins with inning 9
AAKT-CCA8	Game begins with P1 leading 1-0 (1 of 3)
STKT-D0J6	Game begins with P1 leading 1-0 (2 of 3)
8TKT-CLBA	Game begins with P1 leading 1-0 (3 of 3)
REKT-C6V	Game begins with P1 leading 1-0 (4 of 3)
AAKT-CEA8	Game begins with P1 leading 2-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 2-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 2-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 2-0 (4 of 4)
AAKT-CGA8	Game begins with P1 leading 3-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 3-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 3-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 3-0 (4 of 4)
AAKT-CJA8	Game begins with P1 leading 4-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 4-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 4-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 4-0 (4 of 4)
AAKT-CLA8	Game begins with P1 leading 5-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 5-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 5-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 5-0 (4 of 4)
AAKT-CRA8	Game begins with P1 leading 7-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 7-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 7-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 7-0 (4 of 4)
AAKT-CWA8	Game begins with P1 leading 9-0 (1 of 4)
STKT-D0J6	Game begins with P1 leading 9-0 (2 of 4)
8TKT-CLBA	Game begins with P1 leading 9-0 (3 of 4)
REKT-C6VC	Game begins with P1 leading 9-0 (4 of 4)
AEKT-CAA8	Game begins with P2 or computer leading 1-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 1-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 1-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 1-0 (4 of 4)
AJKT-CAA8	Game begins with P2 or computer leading 2-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 2-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 2-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 2-0 (4 of 4)
ANKT-CAA8	Game begins with P2 or computer leading 3-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 3-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 3-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 3-0 (4 of 4)
ATKT-CAA8	Game begins with P2 or computer leading 4-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 4-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 4-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 4-0 (4 of 4)
AYKT-CAA8	Game begins with P2 or computer leading 5-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 5-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 5-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 5-0 (4 of 4)
A6KT-CAA8	Game begins with P2 or computer leading 7-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 7-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 7-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 7-0 (4 of 4)
BEKT-CAA8	Game begins with P2 or computer leading 9-0 (1 of 4)
STKT-D0J6	Game begins with P2 or computer leading 9-0 (2 of 4)
8TKT-CLBA	Game begins with P2 or computer leading 9-0 (3 of 4)
REKT-C6VC	Game begins with P2 or computer leading 9-0 (4 of 4)
AK9T-AAA4	Batter walks on 2 balls (1 of 3)
ALAA-AAEN	Batter walks on 2 balls (2 of 3)
AJET-CABG	Batter walks on 2 balls (3 of 3)
AP9T-AAA4	Batter walks on 3 balls (1 of 3)
ARAA-AAEN	Batter walks on 3 balls (2 of 3)
ANET-CABG	Batter walks on 3 balls (3 of 3)
AZ9T-AAA4	Batter walks on 5 balls (1 of 3)
A0AA-AAEN	Batter walks on 5 balls (2 of 3)
AYET-CABG	Batter walks on 5 balls (3 of 3)
A39T-AAA4	Batter walks on 6 balls (1 of 3)
A4AA-AAEN	Batter walks on 6 balls (2 of 3)
A2ET-CABG	Batter walks on 6 balls (3 of 3)
AK9A-AA9G	Balls do not count, batter never walks
AA3A-AAH4	Unrestricted substitutions for batting team
ABAA-AAA0	Unrestricted substitutions for fielding team (except pitchers)
