DLMA-AA9E	Infinite time
1X4T-BACC	Start course with 25 seconds (1 of 2)
E14T-AACE	Start course with 25 seconds (2 of 2)
1X4T-BACC	Start course with 30 seconds (1 of 2)
GD4T-AACE	Start course with 30 seconds (2 of 2)
1X4T-BACC	Start course with 40 seconds (1 of 2)
JD4T-AACE	Start course with 40 seconds (2 of 2)
1X4T-BACC	Start course with 50 seconds (1 of 2)
LD4T-AACE	Start course with 50 seconds (2 of 2)
1X4T-BACC	Start course with 75 seconds (1 of 2)
R14T-AACE	Start course with 75 seconds (2 of 2)
1X4T-BACC	Start course with 99 seconds (1 of 2)
XH4T-AACE	Start course with 99 seconds (2 of 2)
HXXA-BECR	Extended play adds 25 seconds (1 of 2)
E1XA-AACT	Extended play adds 25 seconds (2 of 2)
HXXA-BECR	Extended play adds 30 seconds (1 of 2)
GDXA-AACT	Extended play adds 30 seconds (2 of 2)
HXXA-BECR	Extended play adds 40 seconds (1 of 2)
JDXA-AACT	Extended play adds 40 seconds (2 of 2)
HXXA-BECR	Extended play adds 50 seconds (1 of 2)
LDXA-AACT	Extended play adds 50 seconds (2 of 2)
HXXA-BECR	Extended play adds 75 seconds (1 of 2)
R1XA-AACT	Extended play adds 75 seconds (2 of 2)
RHXA-A6W8	Extended play adds 99 seconds
ABMA-CAB0	Best frame $100 (original mode) (1 of 2)
AFMA-CAB2	Best frame $100 (original mode) (2 of 2)
ABMA-CAC0	Best engine $100 (original mode) (1 of 2)
AFMA-CAC2	Best engine $100 (original mode) (2 of 2)
AFMA-CADY	Best brakes $100 (original mode)
AFMA-CAET	Best muffler $100 (original mode)
AFMA-CAFT	Best oil $100 (original mode)
AFMA-CAGY	Best tires $100 (original mode)
ALZT-AA98	Accidents don't damage frame (original mode) (1 of 2)
B5LT-AA2C	Accidents don't damage frame (original mode) (2 of 2)
AL0A-AA2C	Accidents don't damage engine (original mode)
AL0A-AA2G	Accidents don't damage brakes (original mode)
AL0A-AA2L	Accidents don't damage muffler (original mode) (1 of 2)
AMLA-AA98	Accidents don't damage muffler (original mode) (2 of 2)
AFMT-AAAC	Advance rank with 1 victory (original mode) (1 of 3)
AFMT-AAC2	Advance rank with 1 victory (original mode) (2 of 3)
AFSA-AAEC	Advance rank with 1 victory (original mode) (3 of 3)
AKMT-AAAC	Advance rank with 2 victories (original mode) (1 of 3)
AKMT-AAC2	Advance rank with 2 victories (original mode) (2 of 3)
AKSA-AAEC	Advance rank with 2 victories (original mode) (3 of 3)
APMT-AAAC	Advance rank with 3 victories (original mode) (1 of 3)
APMT-AAC2	Advance rank with 3 victories (original mode) (2 of 3)
APSA-AAEC	Advance rank with 3 victories (original mode) (3 of 3)
A7MT-AAAC	Advance rank with 7 victories (original mode) (1 of 3)
A7MT-AAC2	Advance rank with 7 victories (original mode) (2 of 3)
A7SA-AAEC	Advance rank with 7 victories (original mode) (3 of 3)
BFMT-AAAC	Advance rank with 9 victories (original mode) (1 of 3)
BFMT-AAC2	Advance rank with 9 victories (original mode) (2 of 3)
BFSA-AAEC	Advance rank with 9 victories (original mode) (3 of 3)
AFMT-AAAY	Drop rank with 1 defeat (original mode)
AKMT-AAAY	Drop rank with 2 defeats (original mode)
APMT-AAAY	Drop rank with 3 defeats (original mode)
A7MT-AAAY	Drop rank with 7 defeats (original mode)
BFMT-AAAY	Drop rank with 9 defeats (original mode)
