AADT-AAGA	Regulation Game lasts 1 inning (1 of 3)
AAEA-AAAC	Regulation Game lasts 1 inning (2 of 3)
ACNA-AACR	Regulation Game lasts 1 inning (3 of 3)
AEDT-AAGA	Regulation Game lasts 2 innings (1 of 3)
AEEA-AAAC	Regulation Game lasts 2 innings (2 of 3)
AGNA-AACR	Regulation Game lasts 2 innings (3 of 3)
AJDT-AAGA	Regulation Game lasts 3 innings (1 of 3)
AJEA-AAAC	Regulation Game lasts 3 innings (2 of 3)
ALNA-AACR	Regulation Game lasts 3 innings (3 of 3)
ATDT-AAGA	Regulation Game lasts 5 innings (1 of 3)
ATEA-AAAC	Regulation Game lasts 5 innings (2 of 3)
AWNA-AACR	Regulation Game lasts 5 innings (3 of 3)
A2DT-AAGA	Regulation Game lasts 7 innings (1 of 3)
A2EA-AAAC	Regulation Game lasts 7 innings (2 of 3)
A4NA-AACR	Regulation Game lasts 7 innings (3 of 3)
RHST-A6Y8	Pitches use less energy (1 of 2)
AHST-BE7A	Pitches use less energy (2 of 2)
RHST-A6Y8	Pitches use more energy (1 of 2)
A5ST-BE7A	Pitches use more energy (2 of 2)
RHST-A6Y8	Pitches use much more energy (1 of 2)
CDST-BE7A	Pitches use much more energy (2 of 2)
BMST-AA7J	Pitches use no energy
AJ3T-AAB2	Batter walks on 2 balls
AN3T-AAB2	Batter walks on 3 balls
AY3T-AAB2	Batter walks on 5 balls
A23T-AAB2	Batter walks on 6 balls
AA3T-AA36	Batter never walks
HT3A-AA9N	Any pitch taken is a ball
4A3T-AA3L	Any pitch taken is a strike
CJ3A-AN9L	Taken strikes do not count (1 of 3)
FA3A-AA96	Taken strikes do not count (2 of 3)
FE3A-BA98	Taken strikes do not count (3 of 3)
9DSA-ACFT	Foul ball after 2 strikes is an out
AXMT-AA7L	Foul bunt after 2 strikes is not an out
AFJT-BA2E	Open Game starts with computer leading 1-0 (1 of 5)
2BJT-ACJG	Open Game starts with computer leading 1-0 (2 of 5)
9BJT-ACJL	Open Game starts with computer leading 1-0 (3 of 5)
GKJT-AD2R	Open Game starts with computer leading 1-0 (4 of 5)
1KJT-BCJN	Open Game starts with computer leading 1-0 (5 of 5)
AFJT-BA2E	Open Game starts with computer leading 2-0 (1 of 5)
2BJT-ACJG	Open Game starts with computer leading 2-0 (2 of 5)
9BJT-ACJL	Open Game starts with computer leading 2-0 (3 of 5)
GKJT-AD2R	Open Game starts with computer leading 2-0 (4 of 5)
VKJT-BCJN	Open Game starts with computer leading 2-0 (5 of 5)
AFJT-BA2E	Open Game starts with computer leading 3-0 (1 of 5)
2BJT-ACJG	Open Game starts with computer leading 3-0 (2 of 5)
9BJT-ACJL	Open Game starts with computer leading 3-0 (3 of 5)
GKJT-AD2R	Open Game starts with computer leading 3-0 (4 of 5)
Z3JT-BCJN	Open Game starts with computer leading 3-0 (5 of 5)
AFJT-BA2E	Open Game starts with P1 leading 4-0 (1 of 5)
2BJT-ACJG	Open Game starts with P1 leading 4-0 (2 of 5)
9BJT-ACJL	Open Game starts with P1 leading 4-0 (3 of 5)
GKJT-AD2R	Open Game starts with P1 leading 4-0 (4 of 5)
6VJT-AGAN	Open Game starts with P1 leading 4-0 (5 of 5)
AFJT-BA2E	Open Game starts with P1 leading 5-0 (1 of 5)
2BJT-ACJG	Open Game starts with P1 leading 5-0 (2 of 5)
9BJT-ACJL	Open Game starts with P1 leading 5-0 (3 of 5)
GKJT-AD2R	Open Game starts with P1 leading 5-0 (4 of 5)
YBJT-BCJN	Open Game starts with P1 leading 5-0 (5 of 5)
AFJT-BA2E	Open Game starts with P1 leading 6-0 (1 of 5)
2BJT-ACJG	Open Game starts with P1 leading 6-0 (2 of 5)
9BJT-ACJL	Open Game starts with P1 leading 6-0 (3 of 5)
GKJT-AD2R	Open Game starts with P1 leading 6-0 (4 of 5)
VBJT-BCJN	Open Game starts with P1 leading 6-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P2 leading 1-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P2 leading 1-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P2 leading 1-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P2 leading 1-0 (4 of 5)
1KJT-BCKG	Exhibition Game starts with P2 leading 1-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P2 leading 2-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P2 leading 2-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P2 leading 2-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P2 leading 2-0 (4 of 5)
VKJT-BCKG	Exhibition Game starts with P2 leading 2-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P2 leading 3-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P2 leading 3-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P2 leading 3-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P2 leading 3-0 (4 of 5)
Z3JT-BCKG	Exhibition Game starts with P2 leading 3-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P1 leading 4-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P1 leading 4-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P1 leading 4-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P1 leading 4-0 (4 of 5)
6VJT-AGBG	Exhibition Game starts with P1 leading 4-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P1 leading 5-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P1 leading 5-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P1 leading 5-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P1 leading 5-0 (4 of 5)
YBJT-BCKG	Exhibition Game starts with P1 leading 5-0 (5 of 5)
AFJT-BA28	Exhibition Game starts with P1 leading 6-0 (1 of 5)
2BJT-ACKA	Exhibition Game starts with P1 leading 6-0 (2 of 5)
9BJT-ACKE	Exhibition Game starts with P1 leading 6-0 (3 of 5)
GKJT-AD3J	Exhibition Game starts with P1 leading 6-0 (4 of 5)
VBJT-BCKG	Exhibition Game starts with P1 leading 6-0 (5 of 5)
