HENA-DEYN	Start with 1 run - P1
HENA-DJYN	Start with 2 runs - P1
HENA-DNYN	Start with 3 runs - P1
HENA-DTYN	Start with 4 runs - P1
HENA-DYYN	Start with 5 runs - P1
HENA-D2YN	Start with 6 runs - P1
HENA-D6YN	Start with 7 runs - P1
HENA-DAYN	Start with 8 runs - P1
HENA-DEZE	Start with 1 run - P2
HENA-DJZE	Start with 2 runs - P2
HENA-DNZE	Start with 3 runs - P2
HENA-DTZE	Start with 4 runs - P2
HENA-DYZE	Start with 5 runs - P2
HENA-D2ZE	Start with 6 runs - P2
HENA-D6ZE	Start with 7 runs - P2
HENA-DAZE	Start with 8 runs - P2
